config/routes.rb
EMpayRssReader::Application.routes.draw do
  get "rssreader/index"

  resources :feedurls

end

app/models/feedentry.rb
class Feedentry < ActiveRecord::Base
  attr_accessible :description, :guid, :link, :publish_at, :title
  belongs_to :Feedurl
  
  
  
  def self.update_feeds()
     logger.info "UPDATE-FEED-1"
    return if(!$UPDATE_FEED)

    $UPDATE_FEED=false

    #############################################
    thread = Thread.new do
      loop do
        logger.info "UPDATE-FEED-2"
        sleep 5.minutes
        #sleep 10
        feedurls = Feedurl.all
        feedurls.each do |feedurl|

          rss = SimpleRSS.parse open(feedurl.feed_url)

          if(rss!=nil && rss.channel.title!=nil)

            rss.entries.each do |entry|
              title = entry.title.gsub(/[^a-z A-Z 0-9 \- ]/,"")
              feedentry = Feedentry.where(title: title, publish_at: entry.pubDate, guid: entry.guid).order('publish_at DESC')

              if(feedentry.empty?)

                feedentry = Feedentry.new
                feedentry.title = title
                feedentry.link = entry.link
                feedentry.publish_at = entry.pubDate
                feedentry.guid = entry.guid
                feedentry.feedurl_id = feedurl.id

                if(feedentry.save)
                  logger.info "NEW FEEDENTRY SAVED!"
                end
              else
                logger.debug "FEED ALREADY AVAILABLE: #{title}"

              end

            end

          end
        end
      end
    end

  #############################################

  end
end

app/models/feedurl.rb
class Feedurl < ActiveRecord::Base
  attr_accessible :feed_title, :feed_url
  has_many :feedentries, dependent: :destroy

  validates :feed_url,  presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  $UPDATE_FEED=true
  Feedentry.update_feeds
end

app/controllers/feedurls_controller.rb
require 'simple-rss'
require 'open-uri'

class FeedurlsController < ApplicationController
  # GET /feedurls
  # GET /feedurls.json
  def index

    logger.debug ".....INDEX...."
    @feedurls = Feedurl.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feedurls }
    end
  end

  # GET /feedurls/1
  # GET /feedurls/1.json
  def show
    @feedurl = Feedurl.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feedurl }
    end
  end

  # GET /feedurls/new
  # GET /feedurls/new.json
  def new
    @feedurl = Feedurl.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @feedurl }
    end
  end

  # GET /feedurls/1/edit
  def edit
    @feedurl = Feedurl.find(params[:id])
  end

  # POST /feedurls
  # POST /feedurls.json
  def create
    rss=nil
    
    # if(params[:feedurl][:feed_url].nil? || params[:feedurl][:feed_url].eql?(""))
      # respond_to do |format|
        # @feedurl = Feedurl.new
        # format.html { render action: "new" }
      # end
      # return
    # end
    
    rss = SimpleRSS.parse open(params[:feedurl][:feed_url]) if(!params[:feedurl][:feed_url].nil? && !params[:feedurl][:feed_url].eql?(""))

    
    if(rss!=nil && rss.channel.title!=nil)
      rss_title = rss.channel.title
      params[:feedurl][:feed_title] = rss_title.gsub(/[^a-z A-Z 0-9 \- ]/,"")
    end

    @feedurl = Feedurl.new(params[:feedurl])

    respond_to do |format|
      if @feedurl.save
        feed_entery(rss, @feedurl)
        format.html { redirect_to @feedurl, notice: 'Feedurl was successfully created.' }
        format.json { render json: @feedurl, status: :created, location: @feedurl }
      else
        format.html { render action: "new" }
        format.json { render json: @feedurl.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /feedurls/1
  # PUT /feedurls/1.json
  def update
    @feedurl = Feedurl.find(params[:id])

    respond_to do |format|
      if @feedurl.update_attributes(params[:feedurl])
        format.html { redirect_to @feedurl, notice: 'Feedurl was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @feedurl.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedurls/1
  # DELETE /feedurls/1.json
  def destroy
    @feedurl = Feedurl.find(params[:id])
    @feedurl.destroy

    respond_to do |format|
      format.html { redirect_to feedurls_url }
      format.json { head :no_content }
    end
  end

  private

  def feed_entery(rss, feedurl)
    rss.entries.each do |entry|
    #puts entry
      feedentry = Feedentry.new
      feedentry.title = entry.title.gsub(/[^a-z A-Z 0-9 \- ]/,"")
      feedentry.link = entry.link
      feedentry.publish_at = entry.pubDate
      feedentry.guid = entry.guid
      feedentry.feedurl_id = feedurl.id

      if(feedentry.save)
        logger.debug "FEEDENTRY SAVED!"
      end
    end
  end

  

end

app/controllers/rssreader_controller.rb
class RssreaderController < ApplicationController
  def index
    @feedentry = Feedentry.order('publish_at DESC').paginate(page: params[:page],  :per_page => 15)
    respond_to do |format|
      format.html # index.html.erb
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def full_title(page_title)
    base_title = "Mukteshwar's RSS Feed Reader"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/feedurls_helper.rb
module FeedurlsHelper
end

app/helpers/rssreader_helper.rb
module RssreaderHelper
end

app/views/feedurls/_form.html.erb
<%= form_for(@feedurl) do |f| %>
  <% if @feedurl.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feedurl.errors.count, "error") %> prohibited this feedurl from being saved:</h2>

      <ul>
      <% @feedurl.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :feed_title %><br />
    <%= f.text_field :feed_title %>
  </div>
  <div class="field">
    <%= f.label :feed_url %><br />
    <%= f.text_field :feed_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feedurls/edit.html.erb
<h1>Update Feed Url</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@feedurl) do |f| %>
     
      <%= f.label :feed_url %>
      <%= f.text_field :feed_url %>

       <%= f.submit "Update", class: "btn btn-large btn-primary" %>
    <% end %>
	<%= link_to 'Back', feedurls_path %>
  </div>
</div>

app/views/feedurls/index.html.erb
<h1>RSS FEED</h1>
<% @feedurls.each do |feedurl| %>
<li>
	<span class="content"><%= feedurl.feed_title %></span>
	<span class="timestamp">Feed URL:</span>
 	<%= link_to 'Show', feedurl %>
    <%= link_to 'Edit', edit_feedurl_path(feedurl) %>
    <%= link_to 'Delete', feedurl, method: :delete, data: { confirm: 'Are you sure?' } %>

</li>
<% end %>
</br>
<!--<%= link_to "New",   new_feedurl_path, :class => "btn btn-large btn-primary" %>-->

<%= button_to "New", new_feedurl_path, :class => "btn btn-large btn-primary", :method => "get" %>
	
	
   

app/views/feedurls/new.html.erb
<h1>New Feed Url</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@feedurl) do |f| %>
       <%= render 'layouts/error_messages', object: f.object %>
      <%= f.label :feed_url %>
      <%= f.text_field :feed_url %>

        
	  <br>
      <%= f.submit "Submit", class: "btn btn-large btn-primary" %>
     
    <% end %>
     <%= link_to 'Back', feedurls_path %>
  </div>
</div>

app/views/feedurls/show.html.erb
<p>
  <b>Feed Url:</b>
  <%= @feedurl.feed_url %>
</p>

<%= link_to 'Edit', edit_feedurl_path(@feedurl) %> |
<%= link_to 'Back', feedurls_path %>

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
	<div class="alert alert-error">
		The form contains <%= pluralize(object.errors.count, "error") %>.
	</div>
	<ul>
		<% object.errors.full_messages.each do |msg| %>
		<li>
			* <%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    -By Mukteshwar Prasad
  </small>
  <nav>
    <ul>
      <li><%= link_to "Feed URL",   feedurls_path %></li>
      <li><%= link_to "RSS Reader", rssreader_index_path %></li>
  	</ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
     
      <nav>
        <ul class="nav pull-right">
           	<li><%= link_to "Feed URL",   feedurls_path %></li>
      		<li><%= link_to "RSS Reader", rssreader_index_path %></li>
          
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%#= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/rssreader/index.html.erb
<h1>RSS FEED - POST</h1>
<% if(@feedentry.empty?)%>
	<span class="content"><h1>NO RSS FEED FOUND!</h1></span>
<%end%>
<% @feedentry.each do |feedentry| %>
<li>
	<span class="content"><a href="<%= feedentry.link%>" target="_blank"><%= feedentry.title %></a></span>
	<span class="timestamp"><%= feedentry.publish_at.to_s[0..(feedentry.publish_at.to_s.length-4)]%></span>
 	

</li>

<% end %>

<%= will_paginate @feedentry %>